name: Star History Chart

on:
  schedule:
    - cron: "0 0 * * 0" # 每周日 UTC 0:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Generate star history
        uses: wanan9999/stars@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          language: zh
          token: ${{ secrets.GH_PAT }}
